### ISSUE TITLE
[BUG]: overridden is not working as expected in sonic_interfaces module. Same issue for l2 & l3 interfaces as well

### ISSUE THREAD

**Issue by kannankvs** [ansible-collections/dellemc.enterprise_sonic#169]
### Bug Description

[ref](https://github.com/ansible-collections/dellemc.enterprise_sonic/blob/main/plugins/module_utils/network/sonic/config/interfaces/interfaces.py)

sonic_interfaces code contains the code for both 'replaced' and for 'overridden'. Seems that the code for 'replaced' is working. But, the code for 'overridden' is not working as expected.

### Product Name

eSONiC AnsibleCollections

### Component or Module Name

sonic_interfaces

### DellEMC Enterprise SONiC Ansible Collection Version

All versions

### SONiC Software Version

All versions

### Configuration

overridden_01:
  module_args:
    state: overridden
    config:
      - name: Eth1/1
        mtu: 1600
  existing_interfaces_config:
    - path: "data/openconfig-interfaces:interfaces"
      response:
        code: 200
        value:
          openconfig-interfaces:interfaces:
            interface:
              - name: 'Eth1/1'
                config:
                  mtu: 2000
              - name: 'Eth1/2'
                config:
                  mtu: 2000

### Steps to Reproduce

By default, all physical interfaces exist. Add some configuration for Eth1/1, Eth1/2, Eth1/3.
Now, if we need to remove the configurations of Eth1/2 and Eth1/3, we need to do overridden for Eth1/1, with the expected params for Eth1/1

### Expected Behavior

Eth1/2, Eth1/3 configs should be removed. ie. They should be set to ALL default values. 
Eth1/1 - config should be replaced with the newly provided config.

### Actual Behavior

It works similar to replaced.

### Logs

NA

**Comment by kerry-meyer** [comment]
The problems reported here have been fixed by the following PR merges:

[Interface - Add support for replaced and overridden states](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/314)

[Change deleted state design for interfaces module](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/310)

[l3_interfaces - Add support for replaced and overridden states](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/221)

[Add support for replaced, overridden states in l2_interfaces module](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/241)
