### ISSUE TITLE
[BUG]: Installation from requirements.yml

### ISSUE THREAD

**Issue by k86td** [ansible-collections/dellemc.enterprise_sonic#192]
### Bug Description

The role doesn't contain a meta/main.yml file, so when downloading it throws an error since it can't parse the requirements.

[Source](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-directory-structure)

### Product Name

SONiC OS

### Component or Module Name

ansible

### DellEMC Enterprise SONiC Ansible Collection Version

any

### SONiC Software Version

irrevelant

### Configuration

Inside **requirements.yml**:

```
- name: dellemc.enterprise_sonic
  src: https://github.com/sonic-net/sonic-restapi.git
  scm: git
```

### Steps to Reproduce

Run `ansible-galaxy install -r requirements.yml`.

### Expected Behavior

No warning should be thrown.

### Actual Behavior

Output:
```yaml
[WARNING]: - dellemc.enterprise_sonic was NOT installed successfully: this role does not appear to have a meta/main.yml file.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

### Logs

```yaml
Starting galaxy role install process
[WARNING]: - dellemc.enterprise_sonic was NOT installed successfully: this role does not appear to have a meta/main.yml file.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by kerry-meyer** [comment]
The collection "name" specified in the requirements.yml shown in this issue belongs to this repo (https://github.com/ansible-collections/dellemc.enterprise_sonic), but the repo specified for cloning in the requirements.yml file is a different repo (https://github.com/sonic-net/sonic-restapi) and is owned by a different organization (SONiC). The README file for that repo provides installation instructions and is not intended for installation by the method used here. Please refer to that README file and, if you encounter any problems, open an issue in that repo.

I am closing this bug because it is opened against the wrong repo.

**Comment by kerry-meyer** [comment]
The collection "name" specified in the requirements.yml shown in this issue belongs to this repo (https://github.com/ansible-collections/dellemc.enterprise_sonic), but the repo specified for cloning in the requirements.yml file is a different repo (https://github.com/sonic-net/sonic-restapi) and is owned by a different organization (SONiC). The README file for that repo provides installation instructions and is not intended for installation by the method used here. Please refer to that README file and, if you encounter any problems, open an issue in that repo.

I am closing this bug because it is opened against the wrong repo.
