### ISSUE TITLE
[FEATURE]: BGP AF Route Aggregation

### ISSUE THREAD

**Issue by fzakfeld** [ansible-collections/dellemc.enterprise_sonic#347]
**Describe the solution you'd like**
I need to configure BGP route aggregation.

e.g.

```
router bgp 64701
...
 address-family ipv6 unicast
  network 2a00:12e8:700:103::/64
  aggregate-address 2a00:12e8:700:103::/64
```

This can be done with the RESTCONF resource `sonic-bgp-global:sonic-bgp-global/BGP_GLOBALS_AF_AGGREGATE_ADDR`

**Describe alternatives you've considered**
Use sonic_api module

**Community Note**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kerry-meyer** [comment]
We will update our sonic_bgp_af resource module to add support for the "aggregate-address" configuration option.

**Comment by kerry-meyer** [comment]
Instead of using the "sonic REST" path shown above, we are implementing this feature using the corresponding Openconfig path:

Example:

path: /openconfig-network-instance:network-instances/network-instance[name=Vrf1]/protocols/protocol[identifier=BGP][name=bgp]/bgp/global/afi-safis/afi-safi[afi-safi-name=IPV6_UNICAST]/aggregate-address-config

payload ={"aggregate-address-config": {"aggregate-address": [{"prefix": "2a00:12e8::/60", "config": {"prefix": "2a00:12e8::/60"}}]}}

**Comment by kerry-meyer** [comment]
This request has been fulfilled by the merging of [Add aggregate address configuration support to BGP AF module #398](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/398).
