### ISSUE TITLE
[BUG]: sonic_interfaces using overridden shuts down all interfaces

### ISSUE THREAD

**Issue by toreanderson** [ansible-collections/dellemc.enterprise_sonic#357]
### Bug Description

When `dellemc.enterprise_sonic.sonic_interfaces` is used with `state: overridden`, it will shut down all interfaces not mentioned in the dict passed to `config:`.

For example, running the following task:

```
- name: Configure interfaces
  tags: sonic_interfaces
  dellemc.enterprise_sonic.sonic_interfaces:
    config:
    - name: Loopback0
      description: Router ID
    - name: Loopback1
      description: Logical VTEP
    - name: Ethernet56
      speed: SPEED_40GB
    - name: Ethernet60
      speed: SPEED_40GB
    - name: Ethernet64
      speed: SPEED_40GB
    - name: Ethernet68
      speed: SPEED_40GB
    state: overridden
```

Results in the following change reported from `ansible-playbook -D`:

```
*** before
--- after
***************
*** 1,7 ****
  [
      {
          'auto_negotiate': false,
!         'enabled': true,
          'fec': 'FEC_DISABLED',
          'mtu': 9100,
          'name': 'Ethernet0',
--- 1,7 ----
  [
      {
          'auto_negotiate': false,
!         'enabled': false,
          'fec': 'FEC_DISABLED',
          'mtu': 9100,
          'name': 'Ethernet0',
```

Note how `Ethernet0` is not mentioned in the `config:` dict, yet it is impacted by this change. So is almost every other interface on the device (including `VlanXX` and `PortChannelXX` interfaces).

This behaviour runs counter to the documentation. In the example using `overridden`, the *before* state shows `Ethernet0` and `Ethernet4` being UP:

https://github.com/ansible-collections/dellemc.enterprise_sonic/blob/882ed0ec0db21907b1282412d87c93e53ee2ee17/plugins/modules/sonic_interfaces.py#L262-L275

The documentation then goes on to show how the `dellemc.enteprise_sonic.sonic_interfaces` is called with a `config` dict that does not mention neither `Ethernet0` nor `Ethernet4`:

https://github.com/ansible-collections/dellemc.enterprise_sonic/blob/882ed0ec0db21907b1282412d87c93e53ee2ee17/plugins/modules/sonic_interfaces.py#L284-L299

Finally, in the *after* state, `Ethernet0` and `Ethernet4` is shown as still UP:

https://github.com/ansible-collections/dellemc.enterprise_sonic/blob/882ed0ec0db21907b1282412d87c93e53ee2ee17/plugins/modules/sonic_interfaces.py#L300-L312

### Product Name

SONiC-OS-4.2.0-Enterprise_Base

### Component or Module Name

sonic_interfaces

### DellEMC Enterprise SONiC Ansible Collection Version

dellemc.enterprise_sonic 2.4.0

### SONiC Software Version

SONiC-OS-4.2.0-Enterprise_Base

### Configuration

CONFIG_FILE() = /home/debian/ansible/ansible.cfg
DEFAULT_HASH_BEHAVIOUR(/home/debian/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/debian/ansible/ansible.cfg) = ['/home/debian/ansible/hosts.yml']
DEFAULT_JINJA2_EXTENSIONS(/home/debian/ansible/ansible.cfg) = jinja2.ext.do
HOST_KEY_CHECKING(/home/debian/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/debian/ansible/ansible.cfg) = auto_silent
MAX_FILE_SIZE_FOR_DIFF(/home/debian/ansible/ansible.cfg) = 1048576
PERSISTENT_COMMAND_TIMEOUT(/home/debian/ansible/ansible.cfg) = 3000

### Steps to Reproduce

See above

### Expected Behavior

Interfaces not mentioned in `config` dict should not be shut down (or the documentation should state that they will be)

### Actual Behavior

Interfaces not mentioned in the `config` dict are shut down.

### Logs

See above

### Screenshots

See above

### Additional Information

This does not happen with dellemc.enterprise_sonic 2.2.0. Testing this version, Ethernet 0 remains UP (in `no shutdown`) after the task has run. It is necessary to upgrade to 2.4.0 to reproduce the bug.

**Comment by kerry-meyer** [comment]
To accomplish the configuration objective that is apparently desired here, "replaced" state would be a better choice.

Overridden state is defined by Ansible as follows:  (REF:    [Network resource module states](https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html))

```
overridden

    Ansible overrides the on-device configuration for the resource with the provided configuration in the task.
 Use caution with this state as you could remove your access to the device (for example, by overriding
 the management interface configuration).
```

The scope of "overridden" state is **all** configuration associated with the specified resource module. It is equivalent to deleting all configuration associated with the resource module, then applying the configuration provided in the triggering "overridden" state "play" (task) in a playbook. We do not recommend using "overridden" state for the "interfaces" resource module. We have modified our implementation of "overridden" state to avoid loss of connectivity over the Management interface (eth0), but for other interfaces, it is implemented according to the specification.

To replace only selected configuration sections for a resource module (e.g. selected interfaces in this case instead of all interfaces), use the "replaced" state.

Ansible's definition for this state (from the same source as the "overridden" definition cited above) is:

```
replaced

    Ansible replaces the on-device configuration subsection with the provided configuration subsection in the task.

```

I agree that the "before/after" states documented for "overridden" state in our current "interfaces" module specification are inaccurate and we will correct this inaccuracy in our documentation.

I will leave this issue open for now to provide a chance for any follow-on questions, answers, and discussion. Please let us know if this explanation is sufficient.

**Comment by toreanderson** [comment]
Part of the issue here is the unexpected change in behaviour between v2.2.0 and v2.4.0. In v2.2.0, the default for `state: overridden` was `no shutdown`, whereas in v2.4.0 it is `shutdown`. This is obviously a change that has an enormous impact (it caused a major outage for us), yet it is not even mentioned in the changelog as far as I can tell.

The default interface state in SONiC is `no shutdown`, i.e., `Ethernet`, `PortChannel` and `Vlan` interfaces are by default admin UP. I would intuitively have expected the module to behave the same. That is, if an interface is not mentioned in the `config` dict, it will be left at (or reverted to) the factory default settings. And indeed, v2.2.0 behaves precisely in that intuitive way.

I also note that the definition of `overridden` you linked to mentions says the module *«would remove all interfaces from the device»* (except the ones mentioned explicitly in the `config` dict, presumably), but v2.4.0 does not do that either (in particular, interfaces such as `Vlan` and `PortChannel` which *could* be removed are left there, but they *are* changed from their default `no shutdown` state to `shutdown`). So v2.4.0's behaviour is neither fish nor fowl in this regard.

**Comment by toreanderson** [comment]
I have also confirmed that this change in default also impacts `state: replaced`.

I start out with a factory default interface as follows:

```
interface Ethernet10
 mtu 9100
 speed 25000
 unreliable-los auto
 no shutdown
 ipv6 enable
```

The I apply the following task:

```
    - name: Configure interfaces
      dellemc.enterprise_sonic.sonic_interfaces:
        config:
        - name: Ethernet10
          description: Eth Ten
        state: replaced
```

With v2.2.0, the resulting change is only the addition of the `description` attribute, while the remaining attributes are left at their factory default values:

```
interface Ethernet10
 description "Eth Ten"
 mtu 9100
 speed 25000
 unreliable-los auto
 no shutdown
 ipv6 enable
```

When doing exactly the same test with v2.4.0, the factory default `no shutdown` attribute gets substituted for `shutdown` (in addition to the expected addition of the `description` attribute), resulting in the following:

```
interface Ethernet10
 description "Eth Ten"
 mtu 9100
 speed 25000
 unreliable-los auto
 shutdown
 ipv6 enable
```

Can this *really* be an intentional change? It seems totally bonkers to intentionally make such a change, especially between two minor versions of the module. If this is not a major breaking change that at the very least is deserving of a major version increase, I do not know what is.

**Comment by kerry-meyer** [comment]
Executive summary, then some details:

I apologize for any inconvenience and downtime caused by the changes made in the enterprise_sonic Ansible resource module collection to implement "replaced" and "overridden" state in release 2.4.0. I understand why you would feel that this should have been declared a major release. We will do what makes sense to adjust our implementation to minimize unnecessary inconvenience in using "replaced" and "overridden" states for "interfaces" in the future. Please note, however, that use of "overridden" state for "interfaces" is still not advised.

For "virtual" (user-created) interface types (including Vlan, Portchannel, and Loopback), the correct default "administrative" ("shutdown") state is "admin. up"/no shutdown. You are correct that this is not the case for the current "interfaces" implementation in our resource module collection. We are taking an action item to fix this for our upcoming release. I will keep this Github issue open until we merge the corresponding fix.

Note: For Ethernet interfaces, the default admin state is "shutdown" (disabled) and this matches our current Ansible implementation, so we do not plan to modify this aspect of the current behavior. (If there is some Enterprise SONiC release you are using that behaves differently, please specify the version.)
****************

More details and responses regarding specific points raised above:

- "Overridden" and "replaced" state were not fully supported for the "interfaces" module until release 2.4.0. The same is true for most of the resource modules in the enterprise_sonic resource module collection. The systematic setting of resource module configuration attributes to default states during replaced/overridden handling (including the "interfaces" resource module) was not added until release 2.4.0. There was no intentional decision to change the admin default. That was just a result of implementing systematic setting of all default values to meet the Ansible specification for "replaced" and "overridden states. I understand from hearing of your experiences related to this change that it might have been advisable to make that release a "major" release because of this consequence.

- For Ethernet interfaces, administrative "shutdown" (disabled) is the "factory default" value for Enterprise SONiC. Because of this, we do not plan to change the Ansible resource module collection behavior for Ethernet interfaces. As requested above: If there is some Enterprise SONiC release you are using that behaves differently, please specify the version.

- For "virtual" (user-created) interface types (including Vlan, Portchannel, and Loopback), this is not the case. The default state is "no shutdown" (enabled) and the current implementation in our resource module is incorrect. We are taking an action item to fix this for our upcoming release.

- Responding to the following statement:
```
I also note that the definition of overridden you linked to mentions says the module «would remove all interfaces 
from the device» (except the ones mentioned explicitly in the config dict, presumably), but v2.4.0 does not do 
that either (in particular, interfaces such as Vlan and PortChannel which could be removed are left there, but they 
are changed from their default no shutdown state to shutdown). So v2.4.0's behaviour is neither fish nor fowl in this 
regard.
```
That sentence in Ansible's documentation is, at best, incomplete. (No networking vendors implement their Ansible resource modules that way.) It would, however be accurate to say:  "...«would remove the configuration from all interfaces on the device»...". In our case, we make an exception for the Management0 interface to avoid an obvious immediate loss of connectivity from the management server. But, as that same sentence says, regarding "overidden" state (just before the part quoted above): "Incorrect use case. This would remove ..."
**************************

Summary: We will fix the current incorrect setting of admin state for interfaces created by the user and will update our documentation to warn users about use of "overridden" state for the "interfaces" resource module.

**Comment by toreanderson** [comment]
Thank you for this update, I think I have a clearer understanding of what happened (and why) now.

My version of Enterprise SONiC does indeed have all Ethernet interfaces in `no shudown` by default, so it surprised me to hear that you say the opposite is the case – but it does make it more understandable why you would hard-code the `sonic_interfaces` module to shut down interfaces by default.

In any case, I am running Enterprise SONiC v4.2.0. Here are the version details from the instances in my GNS3 virtual lab (the hardware devices behave the same though):

```
$ sonic-cli -c 'show version | no-more'
 
Software Version  : 4.2.0-Enterprise_Base
Product           : Generic
Distribution      : Debian 10.13
Kernel            : 5.10.0-21-amd64
Config DB Version : version_4_2_1
Build Commit      : b3aea3ecc9
Build Date        : Wed Nov 29 17:27:27 UTC 2023
Built By          : sonicbld@bld-lvn-csg-06
Platform          : x86_64-kvm_x86_64-r0
HwSKU             : DellEMC-S5248f-P-25G-DPB
ASIC              : vs
Serial Number     : 
Uptime            : 08:26:36 up 8 min, 1 user, load average: 25.45, 20.83, 9.92 
 
REPOSITORY                              TAG                                               IMAGE ID            SIZE
docker-database                         4.2.0-Enterprise_Base                             2a604cf291e1        406MB
docker-database                         latest                                            2a604cf291e1        406MB
docker-dhcp-relay                       4.2.0-Enterprise_Base                             ea3713313189        483MB
docker-dhcp-relay                       latest                                            ea3713313189        483MB
docker-eventd                           4.2.0-Enterprise_Base                             b9c65a415135        401MB
docker-eventd                           latest                                            b9c65a415135        401MB
docker-fpm-frr                          4.2.0-Enterprise_Base                             c033438dec95        515MB
docker-fpm-frr                          latest                                            c033438dec95        515MB
docker-gbsyncd-vs                       4.2.0-Enterprise_Base                             8e352d02f68c        407MB
docker-gbsyncd-vs                       latest                                            8e352d02f68c        407MB
docker-iccpd                            4.2.0-Enterprise_Base                             352b51ea0250        483MB
docker-iccpd                            latest                                            352b51ea0250        483MB
docker-l2mcd                            4.2.0-Enterprise_Base                             708c31fd25da        480MB
docker-l2mcd                            latest                                            708c31fd25da        480MB
docker-lldp                             4.2.0-Enterprise_Base                             c8964a71bdac        485MB
docker-lldp                             latest                                            c8964a71bdac        485MB
docker-macsec                           4.2.0-Enterprise_Base                             c797a75d38c3        421MB
docker-macsec                           latest                                            c797a75d38c3        421MB
docker-nat                              4.2.0-Enterprise_Base                             dd25f40ab851        482MB
docker-nat                              latest                                            dd25f40ab851        482MB
docker-orchagent                        4.2.0-Enterprise_Base                             41412cbfa6cf        475MB
docker-orchagent                        latest                                            41412cbfa6cf        475MB
docker-platform-monitor                 4.2.0-Enterprise_Base                             873e3065c1e0        608MB
docker-platform-monitor                 latest                                            873e3065c1e0        608MB
docker-router-advertiser                4.2.0-Enterprise_Base                             e79a17ce5d4b        400MB
docker-router-advertiser                latest                                            e79a17ce5d4b        400MB
docker-sflow                            4.2.0-Enterprise_Base                             49e9b04fa5c8        481MB
docker-sflow                            latest                                            49e9b04fa5c8        481MB
docker-snmp                             4.2.0-Enterprise_Base                             8366ca57a59c        424MB
docker-snmp                             latest                                            8366ca57a59c        424MB
docker-sonic-mgmt-framework             4.2.0-Enterprise_Base                             0f1ab689b1ee        648MB
docker-sonic-mgmt-framework             latest                                            0f1ab689b1ee        648MB
docker-sonic-telemetry                  4.2.0-Enterprise_Base                             377f6990621a        583MB
docker-sonic-telemetry                  latest                                            377f6990621a        583MB
docker-stp                              4.2.0-Enterprise_Base                             94467f951811        483MB
docker-stp                              latest                                            94467f951811        483MB
docker-syncd-vs                         4.2.0-Enterprise_Base                             10353d9b6f39        407MB
docker-syncd-vs                         latest                                            10353d9b6f39        407MB
docker-tam                              4.2.0-Enterprise_Base                             ad21923fa057        486MB
docker-tam                              latest                                            ad21923fa057        486MB
docker-teamd                            4.2.0-Enterprise_Base                             e74112fd5770        479MB
docker-teamd                            latest                                            e74112fd5770        479MB
docker-udld                             4.2.0-Enterprise_Base                             d73ff7101317        486MB
docker-udld                             latest                                            d73ff7101317        486MB
docker-vrrp                             4.2.0-Enterprise_Base                             8c4b999bf5a4        487MB
docker-vrrp                             latest                                            8c4b999bf5a4        487MB
``` 

Maybe it would be possible for the module to determine the default `shutdown` state used by the specific version, and using that as the default for the `overridden` and `replaced`, instead of hard-coding it?

As for the use of `overridden` not being recommended, I just want to mention that we actually like this method of configuration the most (not just for the `sonic_interfaces` module, but for all of them). The reason for this is that this is the method that most closely resembles declarative configuration management on SONiC, ensuring that the configuration found in our Ansible Git repo is the complete and exact representation the configuration on our devices. If it is not mentioned in the Git repo, we want the factory default settings to be enforced and any orphaned configuration resources to be purged.

The other states leaves the configuration for de-provisioned resources no longer mentioned in the `config` dict in an undefined orphaned state. When the resource is later re-provisioned for some new purpose, it may have unexpected non-default configuration left over from its previous purpose.

(This is of course less of an issue for `sonic_interfaces` when `shutdown` is the default, because then you need to explicitly list all interfaces in active use in the `config` dict anyway, hence `replaced` can be used to ensure interface attributes like MTU are set to the factory defaults unless otherwise specified. The old interface configuration will however be left orphaned and active until the interface is re-provisioned, though, so it is still not as ideal as `overridden`.)

**Comment by kerry-meyer** [comment]
I am researching other options that might help here, using a combination of user configurable settings and Ansible enhancements. I am going to be out of the office for the next week, but will get back to you on this when I return.

**Comment by mingjunzhang2019** [comment]
This issue is fixed.
