### ISSUE TITLE
Upstream SONiC support in addition to Dell EMC Enterprise SONiC support

### ISSUE THREAD

**Issue by bluecmd** [ansible-collections/dellemc.enterprise_sonic#48]
##### SUMMARY

SONiC does not have a good Ansible galaxy module. This one could be it without too much work.

##### ISSUE TYPE

I would like to ask if there are any plans on splitting out the DellEMC specific parts and rebrand the module to being a SONiC-generic module, with DellEMC Enterprise SONiC support?

The way I see it working together on a single SONiC Ansible plugin would benefit SONiC adoption as a whole and help everyone, including DellEMC.

An alternative is to fork this module and strip all the Dell EMC Enterprise SONiC specific things, but that would be a lot of duplicated work and messy to keep synchronized.

**Comment by jeff-yin** [comment]
This is not in the roadmap due to differences in configuration models between the two projects. 

The resource modules in this collection make use of the REST programmatic interface, which in DellEMC Enterprise SONiC is modeled by OpenConfig YANG (and extensions). All features in Enterprise SONiC expose configuration and state with an OC YANG model.

Meanwhile, (Non-DellEMC) SONiC is not prioritizing OC YANG for its features, although we have upstreamed the framework for implementing OC YANG. While SONiC has a programmatic interface, its data model is more of a 1:1 mapping against the Redis DB and that is what feature developers are prioritizing going forward.
